### ISSUE TITLE
migration to cakephp 2.2

### ISSUE THREAD

**Issue by dstok** [bruensicke/flour#3]
Is there anything in the pipeline to move to cakephp 2.2?

**Comment by d1rk** [comment]
Thank you very much for your interest in flour.

Currently there are no plans to convert this plugin to cakephp2 - but it should be not too hard to do it on your own.

I am using lithium more and more lately, so keep an eye on @bruensicke and the repositories over there. Especially lithium_kickstart and li3_kickstart. It may offer some familiar things to you.
